App_Login/urls.py
from django.urls import path
from App_Login import views
from django.contrib.auth import views as auth_views

app_name = 'App_Login'

urlpatterns=[
    path('register/',views.register_attempt,name='register_attempt'),
    path('login/',views.login_attempt,name='login_attempt'),
    path('logout/',views.logout_user,name='logout'),
    path('change-password/',views.change_password,name='change-password'),
    path('subscriber_payment/',views.subscriber_payment,name='subscriber_payment'),
    path('token/',views.token_send,name='token_send'),
    path('success/',views.success,name='success'),
    path('verify/<auth_token>' , views.verify , name="verify"),
    path('error/' , views.error_page , name="error_page"),
    path('register-school/',views.register_school,name='register_school'),
    path('login-school/',views.login_school,name='login_school'),
    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)



]

Index/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('',views.home,name='home'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('services/',views.services,name='services'),
    path('projects/',views.projects,name='projects'),
    path('team/',views.team,name='team'),
    path('faqs/',views.faqs,name='faqs'),
    path('auditorium/',views.auditorium,name='auditorium'),
    path('manual/',views.manual,name='manual'),
    path('events/',views.events,name='events'),
    path('blogs/',views.blogs,name='blogs'),
    path('gallery/',views.gallery,name='gallery'),
    path('contact/',views.contact,name='contact'),
    path('add-exhibition' , views.add_exhibition , name='add_exhibition'),
    path('view-exhibition' , views.View_Exhibition.as_view() , name='view_exhibition'),
    path('exhibition/<pk>/', views.Exhibition_Details.as_view(), name='exhibition_details'),
    path("assignments/", views.assignment, name="assignment"),
    path("school-assignments/", views.school_assignment, name="school_assignment"),
    path("instructions/", views.instructions, name="instructions"),
    path("quiz/", views.quiz, name="quiz"),
    path("task-1/", views.task1, name="task1"),
    path("task-2/", views.task2, name="task2"),
    path("certificate/", views.certificate, name="certificate"),
    path("check-status/", views.status, name="status"),
    path("demo/", views.demo, name="demo"),

]

Savthearth/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns
from django.contrib.auth import views as auth_views
from django.views.static import serve
from django.urls import re_path as url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Index.urls')),
    path('account/', include('App_Login.urls')),
    url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}),
    url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT})
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/forms.py
from django.forms import ModelForm
from django import forms
from App_Login.models import *

from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django_countries import countries
COUNTRY_CHOICES = tuple(countries)

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        exclude = ('user',)

class SignUpForm(UserCreationForm):
    email = forms.EmailField(required=True,help_text='Enter Your Email Address')
    first_name = forms.CharField(max_length=30, required=True,help_text='Enter Your First Name')
    last_name = forms.CharField(max_length=30, required=True,help_text='Enter Your Last Name')
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, required=True,help_text='Choose Your Country')
    phone = forms.CharField(max_length=20, required=True, help_text='Phone number')

    class Meta:
        model = User
        fields = ('email','first_name','last_name','country','phone','username', 'password1', 'password2',)

class UserProfileChange(UserChangeForm):
    class Meta:
        model=User
        fields=('username', 'email', 'first_name', 'last_name', 'password')

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(

            Submit('submit', 'Subscribe', css_class='buton sbutton')
        )

App_Login/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.urls import reverse
from django.http import HttpResponse

from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, logout, authenticate, update_session_auth_hash
from django.conf import settings
from django.core.mail import send_mail

from App_Login.models import *
from App_Login.forms import ProfileForm, SignUpForm, UserProfileChange, SubscriberForm

from django.contrib import messages
import razorpay
import uuid

from django.core.mail import EmailMultiAlternatives
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.template.loader import render_to_string
from django.core.mail import EmailMessage


def register_attempt(request):

    if request.method == 'POST':
        fullname = request.POST.get('fullname')
        dob = request.POST.get('dob')
        email = request.POST.get('email')
        contact = request.POST.get('contact')
        acontact = request.POST.get('acontact')
        student_class = request.POST.get('student_class')
        school = request.POST.get('school')
        country = request.POST.get('country')
        city = request.POST.get('city')
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(fullname)
        print(dob)
        # print(gender)
        print(contact)
        print(country)
        print(city)
        print(student_class)

        try:
            if User.objects.filter(username = username).first():
                messages.success(request, 'Username is taken.')
                return HttpResponseRedirect(reverse('App_Login:register_attempt'))

            if User.objects.filter(email = email).first():
                messages.success(request, 'Email is taken.')
                return HttpResponseRedirect(reverse('App_Login:register_attempt'))


            user_obj = User(username = username , email = email)
            user_obj.set_password(password)
            user_obj.save()
            auth_token = str(uuid.uuid4())
            profile_obj = Profile.objects.create(user = user_obj , auth_token = auth_token, fullname = fullname,student_class=student_class, dob=dob, contact=contact, country=country, city=city, email=email,school=school,acontact=acontact)
            profile_obj.save()
            messages.success(request, 'Registered Sucessfully')
            html_template = render_to_string('register_email.html', {'fullname':fullname, 'username':username,'password':password})
            recipient_list = [email]
            message = EmailMessage('Welcome To SAVTHEARTH', html_template,
                                   'SAVTHEARTH <info@savthearth.org>', [email])
            message.content_subtype = 'html'
            message.send()
            profile_obj.save()

            return HttpResponseRedirect(reverse('App_Login:login_attempt'))


        except Exception as e:
            print(e)


    return render(request , 'App_Login/register.html')

def login_attempt(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_obj = User.objects.filter(username = username).first()
        if user_obj is None:
            messages.success(request, 'User not found.')
            return HttpResponseRedirect(reverse('App_Login:login_attempt'))


        # profile_obj = Profile.objects.filter(user = user_obj ).first()
        #
        # if not profile_obj.is_verified:
        #     messages.success(request, 'Profile is not verified check your mail.')
        #     return HttpResponseRedirect(reverse('App_Login:login_attempt'))

        user = authenticate(username = username , password = password)
        if user is None:
            messages.success(request, 'Wrong password.')
            return HttpResponseRedirect(reverse('App_Login:login_attempt'))

        login(request , user)
        return HttpResponseRedirect(reverse('assignment'))

    return render(request , 'App_Login/login.html')

def register_school(request):

    if request.method == 'POST':
        school_name = request.POST.get('school_name')
        city = request.POST.get('city')
        country = request.POST.get('country')
        principal_name = request.POST.get('principal_name')
        teacher_incharge = request.POST.get('teacher_incharge')
        mobile_number = request.POST.get('mobile_number')
        landline_number = request.POST.get('landline_number')
        student_strength = request.POST.get('student_strength')
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        print(school_name)
        print(city)
        print(country)
        print(principal_name)
        print(teacher_incharge)
        print(mobile_number)
        print(landline_number)
        print(student_strength)
        print(username)
        print(password)
        print(email)


        try:
            if User.objects.filter(username = username).first():
                messages.success(request, 'Username is taken.')
                return HttpResponseRedirect(reverse('App_Login:register_attempt'))

            if User.objects.filter(email = email).first():
                messages.success(request, 'Email is taken.')
                return HttpResponseRedirect(reverse('App_Login:register_attempt'))


            user_obj = User(username = username , email = email)
            user_obj.set_password(password)
            user_obj.save()
            profile_obj = School_Profile.objects.create(user = user_obj , school_name=school_name, city=city, country=country, principal_name=principal_name, teacher_incharge=teacher_incharge, mobile_number=mobile_number, landline_number=landline_number, student_strength=student_strength, email=email)
            profile_obj.save()
            messages.success(request, 'Registered Sucessfully')
            # html_content = render_to_string("email_template.html",{'username':username,'password':password})
            # text_content = strip_tags(html_content)
            #
            # email_send = EmailMultiAlternatives(
            #     "ICFC Confirmation Email",
            #     text_content,
            #     settings.EMAIL_HOST_USER,
            #     [email],
            # )
            # email_send.attach_alternative(html_content,"text/html")
            # email_send.send()
            # print(email_send)
            return HttpResponseRedirect(reverse('App_Login:login_school'))


        except Exception as e:
            print(e)


    return render(request , 'App_Login/register_school.html')


def login_school(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user_obj = User.objects.filter(username = username).first()
        if user_obj is None:
            messages.success(request, 'User not found.')
            return HttpResponseRedirect(reverse('App_Login:login_attempt'))


        # profile_obj = Profile.objects.filter(user = user_obj ).first()
        #
        # if not profile_obj.is_verified:
        #     messages.success(request, 'Profile is not verified check your mail.')
        #     return HttpResponseRedirect(reverse('App_Login:login_attempt'))

        user = authenticate(username = username , password = password)
        if user is None:
            messages.success(request, 'Wrong password.')
            return HttpResponseRedirect(reverse('App_Login:login_school'))

        login(request , user)
        return HttpResponseRedirect(reverse('school_assignment'))

    return render(request , 'App_Login/login_school.html')


@login_required
def logout_user(request):
    logout(request)
    messages.warning(request,"You Are Logged Out!")
    return HttpResponseRedirect(reverse('home'))

@login_required
def change_password(request):
    if request.method == 'POST':
        fm = PasswordChangeForm(user=request.user, data=request.POST)
        if fm.is_valid():
            fm.save()
            update_session_auth_hash(request, fm.user)
            return HttpResponseRedirect(reverse('App_Login:login'))
    else:
        fm = PasswordChangeForm(user=request.user)
    return render(request, 'App_Login/change-password.html', {'form':fm})

@login_required(login_url='/account/login')
def subscriber_payment(request):
    if request.method == 'POST':
        subs = request.user;
        amount = 500000;
        client = razorpay.Client(auth=('rzp_test_uxpXt2M6OCK6fN','UgT5LV4PMBIS6JBV5nLcLBcu'))

        response_payment = client.order.create(dict(amount=amount, currency='INR'))
        order_id = response_payment['id']
        order_status = response_payment['status']
        if order_status == 'created':
            subscriber = Subscriber(
                subs = subs,
                order_id = order_id
            )
            subscriber.save()
            response_payment['name']: request.user
            form = SubscriberForm(request.POST or None)
            return render(request, 'App_Login/subscriber_payment.html', {'form':form, 'payment':response_payment})
    form = SubscriberForm()
    return render(request, 'App_Login/subscriber_payment.html', {'form':form})

def success(request):
    return render(request,'App_Login/success.html')

def token_send(request):
    return render(request,'App_Login/token_send.html')

def verify(request , auth_token):
    try:
        profile_obj = Profile.objects.filter(auth_token = auth_token).first()


        if profile_obj:
            if profile_obj.is_verified:
                messages.success(request, 'Your account is already verified.')
                return HttpResponseRedirect(reverse('App_Login:login_attempt'))

templates/App_Login/add_profile.html
{% extends 'layouts.html' %}
{% load crispy_forms_tags %}
{% block title %}
Add Profile
{% endblock %}

{% block css_block %}
<style>
  .add_profile{
    width:1000px;
    border:1px solid #ccc;
    padding-top:80px;
    padding-bottom:40px;
  }

</style>
{% endblock %}
{% block content %}
<center>
<div class="add_profile">
  <h2>Add Profile: </h2>
  <form class="container" method="post">
    {{ form|crispy}}
    {% csrf_token %}
<br>
  <a href="{% url 'App_Login:profile' %}" class="btn btn-warning btn-sm">Add Profile</a>
<br>
  </form>
</div>

{% endblock %}

templates/App_Login/change-password.html
{% extends 'layouts.html' %}
{% load crispy_forms_tags %}
{% block title %}
Change Password
{% endblock %}

{% block content %}
<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">

</section><!-- End Breadcrumbs -->

<center>
<!-- <div class="line">

</div> -->
<div class="login_top">
  <h2>Change Your Password!</h2><br>
  <form class="container" method="POST">
    {{ form|crispy}}
    {% csrf_token %}
<br>
  <button type="submit" class="btn btn-success btn-sm" >Change</button>

  </form>
</div>
<div class="login_bottom">


</div>
{% endblock %}

templates/App_Login/error.html
{% extends "layouts.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Error Page
{% endblock %}
{% block style %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="{% static 'css/register.css'%}" rel="stylesheet">
{% endblock %}

    {% block content %}


    <div class="global-container" style="background-size:cover">
        <div class="card login-form">
        <div class="card-body">
          <center>
            <h3 class="card-title ">Error</h3>
            <a href="/" class="btn btn-success btn-login" style="margin-top:5px;">Back</a>


            </div>
        </div>
    </div>
    </div>


    {% endblock %}

templates/App_Login/login.html
{% extends "layouts.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Login Account
{% endblock %}
{% block style %}

<link href="{% static 'css/register.css'%}" rel="stylesheet">
<style media="screen">
  .alert{
    margin-bottom: 0px;
text-align: center;
font-size: 1rem;
  }
</style>
{% endblock %}

    {% block content %}

    {% if user.is_authenticated %}
    <div class="global-container" style="background-size:cover">
        <div style="width:450px" class="card login-form">
        <div class="card-body">
            <h3  class="card-title text-center">You are already logged in.</h3>
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}

        {% endif %}
            <div class="card-text">
                <!--
                <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->

            </div>
        </div>
    </div>
    </div>
    {% else %}
    <div class="global-container" style="background-size:cover">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Student <br>Login Account </h3>
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}

        {% endif %}
            <div class="card-text">
                <!--
                <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->
                <form method="post" >
                    {% csrf_token %}
                    <!-- to error: add class "has-danger" -->
                    <div class="form-group">
                        <label class="login-label" for="exampleInputEmail1">Username <i class="fa fa-user"></i></label>
                        <input type="text" name="username" class="form-control form-control-sm login-input" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label class="login-label" for="exampleInputPassword1">Password <i class="fa fa-lock"></i></label>

                        <input type="password" name="password" class="form-control form-control-sm login-input" id="exampleInputPassword1">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block btn-login">Sign in</button>

                    <div class="sign-up">
                      <a href="{% url 'App_Login:register_attempt' %}">Create Account</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>

    {% endif %}


    {% endblock %}

templates/App_Login/login_school.html
{% extends "layouts.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Login Account
{% endblock %}
{% block style %}

<link href="{% static 'css/register.css'%}" rel="stylesheet">
<style media="screen">
  .alert{
    margin-bottom: 0px;
text-align: center;
font-size: 1rem;
  }
</style>
{% endblock %}

    {% block content %}

    {% if user.is_authenticated %}
    <div class="global-container" style="background-size:cover">
        <div style="width:450px" class="card login-form">
        <div class="card-body">
            <h3  class="card-title text-center">You are already logged in.</h3>
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}

        {% endif %}
            <div class="card-text">
                <!--
                <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->

            </div>
        </div>
    </div>
    </div>
    {% else %}
    <div class="global-container" style="background-size:cover">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">School <br>Login Account </h3>
            {% if messages %}

            {% for message in messages %}
            <div class="alert alert-info">
                {{ message }}
            </div>
            {% endfor %}

        {% endif %}
            <div class="card-text">
                <!--
                <div class="alert alert-danger alert-dismissible fade show" role="alert">Incorrect username or password.</div> -->
                <form method="post" >
                    {% csrf_token %}
                    <!-- to error: add class "has-danger" -->
                    <div class="form-group">
                        <label class="login-label" for="exampleInputEmail1">Username <i class="fa fa-user"></i></label>
                        <input type="text" name="username" class="form-control form-control-sm login-input" id="exampleInputEmail1" aria-describedby="emailHelp">
                    </div>
                    <div class="form-group">
                        <label class="login-label" for="exampleInputPassword1">Password <i class="fa fa-lock"></i></label>

                        <input type="password" name="password" class="form-control form-control-sm login-input" id="exampleInputPassword1">
                    </div>
                    <button type="submit" class="btn btn-primary btn-block btn-login">Sign in</button>

                    <div class="sign-up">
                      <a href="{% url 'App_Login:register_school' %}">Create Account</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
    </div>

    {% endif %}


    {% endblock %}

templates/App_Login/profile.html
{% extends 'layouts.html' %}
{% load crispy_forms_tags %}
{% block title %}
Profile Page
{% endblock %}
{% block body_block %}
{% block css_block %}
<style>
  .profile{
    width:1000px;
    border:1px solid #ccc;
    padding-top:80px;
    padding-bottom:40px;
  }

</style>
{% endblock %}
<div class="profile">
  <h2>Your Profile: </h2><br>

  <p>Username: {{user.username}}</p>
  <p>Email: {{user.email}}</p>
  <p>Name: {{user.full_name}}</p>
  <p>Address: {{user.address_1}}</p>
  <p>City: {{user.city}}</p>
  <p>Zipcode: {{user.zipcode}}</p>
  <p>Country: {{user.country}}</p>
  <p>Contact No.: {{user.phone}}</p>
  <br>
  <a href="{% url '' %}" class="btn btn-warning btn-sm">Change Profile User</a>

</div>

{% endblock %}

templates/App_Login/subscriber_payment.html
{% extends 'layouts.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Subscribe
{% endblock %}

{% block content %}
<div class="padding">
  <center>
  <h2>Subscribe</h2>
  <div class="container">
    {% crispy form %}
  </div>
  {% if payment %}
  <form class="text-center border border-light p-2 " style="width: 10%;
    margin-top: 1%;" action="{% url 'payment_status'%}" method="POST">
      {% csrf_token %}

      <!-- <p class="h3 mb-3"><i class="fas fa-coffee"></i> BUY ME A COFFEE!!</p>
      <p class="mb-3">Help us create more videos by donating 500 INR</p>

      <input type="name" name="name" id="name" required class="form-control mb-4" placeholder="Name"> -->

      <!-- RAZORPAY INTEGRATION HERE -->
      <script src="https://checkout.razorpay.com/v1/checkout.js"
      data-key="rzp_test_uxpXt2M6OCK6fN"
      data-amount="{{payment.amount}}"
      data-currency="{{payment.currency}}"
      data-order_id="{{payment.id}}"
      data-buttontext="Join Now"
      data-name="Indican"
      data-description="Membership"
      data-image="{% static 'img/logo3.png'%}"
      data-prefill.name="{{payment.name}}"
      data-prefill.email=""
      data-theme.color="#CDA45E"></script>
      <input type="hidden" custom="Hidden Element" name="hidden">
  </form>
  {% endif %}
</div>


{% endblock %}

templates/App_Login/success.html
{% extends "layouts.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Success Page
{% endblock %}
{% block style %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="{% static 'css/register.css'%}" rel="stylesheet">
{% endblock %}

    {% block content %}



    <div class="global-container" style="background-size:cover">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">Hurray your mail is verified! </h3>
            <div class="card-text text-center card-text1" >
                Please login
            </div>
            <div class="text-center">
            <a class="btn btn-primary btn-login" href="{% url 'App_Login:login_attempt'%}" >Login</a>
</div>
        </div>
    </div>
    </div>


    {% endblock %}

templates/App_Login/token_send.html
{% extends "layouts.html"%}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}
Token Send
{% endblock %}
{% block style %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link href="{% static 'css/register.css'%}" rel="stylesheet">
{% endblock %}

    {% block content %}

    <div class="global-container" style="background-size:cover">
        <div class="card login-form">
        <div class="card-body">
            <h3 class="card-title text-center">We have sent an email to you </h3>
            <div class="card-text text-center card-text1" >
                Please check your mail
            </div>
        </div>
    </div>
    </div>


    {% endblock %}